"""Visualisation helpers (animation, plotting)."""

from geometrodynamics.viz.antipodal_crossing import (
    AntipodalCrossingSim,
    Absorption,
    Crossing,
    run_animation,
)
from geometrodynamics.viz.antipodal_focusing import (
    PlaneWaveSim,
    SphereWaveSim,
    RefocusResult,
    focusing_factor,
    measure_refocus,
    draw_contrast,
    draw_focus_object,
    draw_focusing_factor,
    plot_contrast_panel,
    plot_focusing_panel,
    plot_object_panel,
    run_animation as run_focusing_animation,
)
from geometrodynamics.viz.throat_wavefront import (
    Arrival,
    BareSphereSim,
    ThroatGeometry,
    ThroatWaveSim,
    draw_geometry,
    draw_hemispheres,
    draw_map,
    draw_neck_strip,
    export_frames,
    measure_bulk_precursor,
    measure_echo_delay,
    measure_focus,
    measure_orientation_visibility,
    measure_mouth_budget,
    mirror_symmetry_broken,
    orientation_parity,
    peak_in_window,
    plot_wavefront_panel,
    sphere_image,
    surface_name,
    measure_arrival_multiplicity,
    watch_point,
    Multiplicity,
    run_animation as run_throat_animation,
)
from geometrodynamics.viz.geometry_panels import (
    draw_green,
    draw_handshake,
    draw_hopf,
    draw_throat,
    plot_green_panel,
    plot_handshake_panel,
    plot_hopf_panel,
    plot_throat_panel,
    run_dashboard,
)

__all__ = [
    "AntipodalCrossingSim",
    "Absorption",
    "Crossing",
    "run_animation",
    # antipodal focusing
    "PlaneWaveSim",
    "SphereWaveSim",
    "RefocusResult",
    "focusing_factor",
    "measure_refocus",
    "draw_contrast",
    "draw_focus_object",
    "draw_focusing_factor",
    "plot_contrast_panel",
    "plot_focusing_panel",
    "plot_object_panel",
    "run_focusing_animation",
    # throat wavefront (ring wavefronts on a surface with a handle)
    "Arrival",
    "BareSphereSim",
    "ThroatGeometry",
    "ThroatWaveSim",
    "draw_geometry",
    "draw_hemispheres",
    "draw_map",
    "draw_neck_strip",
    "export_frames",
    "measure_bulk_precursor",
    "measure_echo_delay",
    "measure_focus",
    "measure_orientation_visibility",
    "measure_mouth_budget",
    "mirror_symmetry_broken",
    "orientation_parity",
    "peak_in_window",
    "plot_wavefront_panel",
    "sphere_image",
    "surface_name",
    "measure_arrival_multiplicity",
    "watch_point",
    "Multiplicity",
    "run_throat_animation",
    # geometry panels
    "draw_green",
    "draw_handshake",
    "draw_hopf",
    "draw_throat",
    "plot_green_panel",
    "plot_handshake_panel",
    "plot_hopf_panel",
    "plot_throat_panel",
    "run_dashboard",
]
